export const portfolioItems = [
  {
    id: 'saas-dashboard',
    label: 'SaaS Dashboard',
    tag: 'Web App',
    description: 'Analytics-heavy dashboard with real-time data, role-based access, and a clean dark UI.',
    accent: 'from-[#7c3aff] to-[#3a1a6e]',
    highlight: '#a56dff',
    mockup: 'dashboard',
  },
  {
    id: 'landing-page',
    label: 'Startup Landing Page',
    tag: 'Marketing',
    description: 'High-converting landing page with animated hero, feature sections, and clear CTAs.',
    accent: 'from-[#ff4fd8] to-[#7c1fa0]',
    highlight: '#ff79ff',
    mockup: 'landing',
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce Storefront',
    tag: 'E-Commerce',
    description: 'Product-focused storefront with cart, filters, and a smooth checkout experience.',
    accent: 'from-[#0ea5e9] to-[#1e3a5f]',
    highlight: '#38bdf8',
    mockup: 'ecommerce',
  },
  {
    id: 'crm-portal',
    label: 'CRM Client Portal',
    tag: 'Automation',
    description: 'Internal CRM portal with lead tracking, pipeline views, and automated follow-up triggers.',
    accent: 'from-[#10b981] to-[#064e3b]',
    highlight: '#34d399',
    mockup: 'crm',
  },
  {
    id: 'portfolio-site',
    label: 'Creative Portfolio',
    tag: 'Design',
    description: 'Bold portfolio site with motion, full-bleed imagery, and a memorable visual identity.',
    accent: 'from-[#f59e0b] to-[#78350f]',
    highlight: '#fbbf24',
    mockup: 'portfolio',
  },
  {
    id: 'booking-app',
    label: 'Booking & Scheduling',
    tag: 'Web App',
    description: 'Appointment booking UI with calendar, availability logic, and confirmation flows.',
    accent: 'from-[#f43f5e] to-[#4c0519]',
    highlight: '#fb7185',
    mockup: 'booking',
  },
]